### ISSUE TITLE
Admin Imio , Amélioration de l'ergonomie

### ISSUE THREAD

**Issue by ndufrane** [Geode/imio_geonode#11]
- [x] Passer le texte en header avec margin par rapport à la barre de menu.
- [x] Ajouter une aide à l'encodage pour add urb sous forme de input avec pré-texte grisé.
- [x] Rendre visible les erreurs de valdation coté serveur dans le formulaire

**Comment by teamgeode** [comment]
Ok reste a bien tester les notifications
