### ISSUE TITLE
Meilleure récupération des erreurs lors de la récupération des données (add_urb)

### ISSUE THREAD

**Issue by ndufrane** [Geode/imio_geonode#14]
Pour le moment : si une erreur est survenue l'utilisateur reçois le message suivant (ce qui est correct)
Erreur de connexion au Geoserver lors de la création du DataStore

A voir si il ne serait pas intéressant de renseigner en plus l'erreur source :
Tried to create workspace but got 500: :Namespace with URI 'imio.be' already exists.

Autre exemple 
Message : Erreur lors de l'importation des couches depuit Geoserver
Erreur source :Group matching query does not exist.

**Comment by teamgeode** [comment]
ok
