### ISSUE TITLE
Script d'ajout de commune

### ISSUE THREAD

**Issue by ndufrane** [Geode/imio_geonode#8]
Ce qu'il faut faire :
1 créer un datastore sur le schéma URB
2 publier avec les bon SLD les couches urban nécessaires
3 updatelayers dans geonode
4 créer un groupe du nom de commune
5 créer un user administrateur du groupe
6 setter des droits sur les couches (RO pour le groupe et Write pour metadata et style à l'admin)

Il faudrait découper ça dans les tâches suivantes :

1- créer dans le backend d'administration un bouton permettant d'exécuter un python manage.py updatelayers (http://stackoverflow.com/questions/6250970/run-custom-admin-command-from-view) uniquement pour les ADMIN
2- Automatiser la création d'un groupe et de d'un user admin du groupe avec comme param le nom de la commune voir #9 
3- Appeler le script addurb.py depuis la mm interface (https://github.com/Geode/vagrant_imio_geonode/blob/master/setup/addurb.py)
4- Finaliser le script addurb.py (debug pour le moment il plante sur la publication du layer) --> Je vais dabord y regarder histoire de finir ce que j'ai commencé, mais il est probable que j'ai besoin d'aide...
5- Gérer les droits sur la liste des couches importées.

**Comment by teamgeode** [comment]
Les différent point sont present.
(reste a vérifier le CSRF_token)

**Comment by ndufrane** [comment]
Il manque capa au minimum dans geoserver et ensuite la procédure "plante" : {'success': False, 'error': "'Layer' object has no attribute '**getitem**'"}

**Comment by ndufrane** [comment]
ok
