### ISSUE TITLE
Automatisation de la création d'utilisateur lors de l'ajout d'une commune

### ISSUE THREAD

**Issue by ndufrane** [Geode/imio_geonode#9]
Voir ticket #8 

Deux groupes doivent être créés 
-> commune_ro
-> commune_rw

Deux utilisateurs doivent être ajoutés:
-> commune_user (commune_ro)
-> commune_admin (isStaff) (commune_rw + commune_ro)

Le but est d'effectuer ces opérations en 1 seule fois

**Comment by teamgeode** [comment]
Pourquoi crée 2 groupes ?

Si on a 1 groupes avec des utilisateur lambda en RO et un manager en RW es ce que ce ne sera pas assez ?

**Comment by collaer** [comment]
ça pourrait marcher en temps t0 mais ensuite c'est plus lourd.

Deux groupes ça facilite la gestion, le manager a toujours son backup et il
peut changer, c'est plus simple de mettre un nouveau user dans un groupe
que de définir pour toutes les couches / cartes des droits pour un nouveau
user.

**Comment by teamgeode** [comment]
Méthode qui prend en paramétré un nom d'utilisateur et un nom de commune
37573d2ac81b5fb7f078020a5a6c7494dbbec3b1 

Ex si utilisateur Paul et commune Commu
User : 
--- Commu_Paul
--- Commu_admin (staff)
Groupe : 
--- Commu_ro (Commu_admin (manager du groupe) + Commu_Paul)
--- Commu_rw (Commu_admin (manager du groupe))

Si c'est ok on peut fermer l'issue

**Comment by ndufrane** [comment]
A tester mais ca me parait ok

2015-03-05 15:28 GMT+01:00 teamgeode notifications@github.com:

**Comment by teamgeode** [comment]
testé et fonctionnelle.

**Comment by ndufrane** [comment]
Ok
